In [28]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [8]:
import pandas as pd
df=pd.read_csv('/Users/naekid/Downloads/infectionrisk.txt', delimiter='\t')
df = df[df['Stay']<=14]
df = pd.concat([df, pd.get_dummies(df['Region'])], axis=1);
region_mapping = {1:'NE',2:'NC', 3:'S', 4:'W'}
df.rename(columns=region_mapping).head()
df = df.rename(columns=region_mapping)

In [27]:
df.head()

,ID,Stay,Age,InfctRsk,Culture,Xray,Beds,MedSchool,Region,Census,Nurses,Facilities,NE,NC,S,W
0,1,7.13,55.7,4.1,9.0,39.6,279,2,4,207,241,60.0,0,0,0,1
1,2,8.82,58.2,1.6,3.8,51.7,80,2,2,51,52,40.0,0,1,0,0
2,3,8.34,56.9,2.7,8.1,74.0,107,2,3,82,54,20.0,0,0,1,0
3,4,8.95,53.7,5.6,18.9,122.8,147,2,4,53,148,40.0,0,0,0,1
4,5,11.20,56.5,5.7,34.5,88.9,180,2,1,134,151,40.0,1,0,0,0

In [17]:
model_1 = ols('InfctRsk ~ Stay + Xray + C(Region)', data=df).fit()

In [26]:
sm.stats.anova_lm(model_1)

              df      sum_sq    mean_sq          F        PR(>F)
C(Region)    3.0   10.928549   3.642850   3.393540  2.069619e-02
Stay         1.0   60.221045  60.221045  56.099640  2.249344e-11
Xray         1.0   10.404607  10.404607   9.692537  2.384438e-03
Residual   105.0  112.713908   1.073466        NaN           NaN

In [23]:
model_2 = ols('InfctRsk ~ Stay + Xray', data=df).fit()
sm.stats.anova_lm(model_2, model_1)

   df_resid         ssr  df_diff    ss_diff         F    Pr(>F)
0     108.0  123.562463      0.0        NaN       NaN       NaN
1     105.0  112.713908      3.0  10.848555  3.368701  0.021352

In [25]:
model_3 = ols('InfctRsk ~ Stay + Xray + W', data=df).fit()
sm.stats.anova_lm(model_3, model_1)

   df_resid         ssr  df_diff   ss_diff         F    Pr(>F)
0     107.0  113.113400      0.0       NaN       NaN       NaN
1     105.0  112.713908      2.0  0.399492  0.186076  0.830484